### ISSUE TITLE
wifi Intel 

### ISSUE THREAD

**Issue by manhlab** [jardenliu/XPS15-9560-Ventura#134]
We can use this config to use wifi Intel
https://www.youtube.com/watch?v=zA7k13i8dTg&feature=youtu.be&fbclid=IwAR1ezG3RO7jHJe5_U_96cCvlaOsp4S-z0IJsL7BsxUh0xK7WNHhelDCxAF4

**Comment by jardenliu** [comment]
This intel wifi kext is still under development. and does not support most intel wifi. Can't connect encrypted wifi networki.

**Comment by intel0753** [comment]
> We can use this config to use wifi Intel

It might be considered once this method is stable and easy to use. Currently, this driver only supports limited Intel WiFi card and it is hard to use and it now just has limited support for WPA2 encrypted WiFi. Just see how it will be developed.
