### ISSUE TITLE
Fan always running

### ISSUE THREAD

**Issue by albatrosify** [jardenliu/XPS15-9560-Ventura#135]
The ventilation fan is constantly running even at low CPU temp without any user input.
(at comparable load the fan would be switched off in windows).

Is there any chance how to fix this?

OffTopic: Many many thanks to you for sharing your settings. 
This made installing and running Catalina incredibly easy. :)

**Comment by albatrosify** [comment]
So I've let the computer idle for quite some time and tried after another restart.
Fan stays off. So this is just a thermal issue. 

Two Questions: Are all functions enabled to help the laptop use as less energy as possible? CPU throttling .etc?
2nd question regarding nvidia optimus. Is the dGPU completely deactivated so it doesnt draw any power? or is it possible to do that?
I've noticed a relatively fast battery drain compared to windows.

**Comment by SilentSliver** [comment]
1. I don’t know. 
2. DGPU is  disabled by ACPI method. I think it’s be disabled totally.

**Comment by albatrosify** [comment]
1. Undervolting helped quite a lot to me. 
You can try voltageshift. My values were -130 -100 -120
Fan stayed off most of the times now.
