### ISSUE TITLE
No Sound on Headphone

### ISSUE THREAD

**Issue by albatrosify** [jardenliu/XPS15-9560-Ventura#136]
When I plug in headphones, system recognizes the headphones and system settings show (Headaphones) instead of "Speakers".
However no sound audible on headphones.

**Comment by SilentSliver** [comment]
If you can provide how this happened or your environment would be more helpful. 
My earphone works perfectly on my 9560.
I heard that some earphones will be silent due to the wrong info when be identified by macOS.

**Comment by albatrosify** [comment]
I first installed OSX with default config of unibeast. after install tried some other bootloader package and finally replaced with yours. I will re-install again as I am receiving Dell DW-1820A and will check again with a clean setup if headphone sound is still broken.

**Comment by mhoppi** [comment]
Update:
Sound is audible on headphones but incredibly silent.
At maximum volume it is almost inaudible.

**Comment by marcoscaco** [comment]
> Update:
> Sound is audible on headphones but incredibly silent.
> At maximum volume it is almost inaudible.

I have this problem too, but the latest update fixed the SD reader and the sound to me!
try the latest EFI provide for clover

**Comment by AntSYau** [comment]
I fixed this problem by running `sudo kextcache -i /` in terminal and reboot.

**Comment by nmnobre** [comment]
> > Update:
> > Sound is audible on headphones but incredibly silent.
> > At maximum volume it is almost inaudible.
> 
> I have this problem too, but the latest update fixed the SD reader

Is this visible in the "About this Mac" menu?

> and the sound to me!
> try the latest EFI provide for clover

**Comment by nmnobre** [comment]
> Update:
> Sound is audible on headphones but incredibly silent.
> At maximum volume it is almost inaudible.

+1 w/ the exact same issue
