### ISSUE TITLE
OpenCore?

### ISSUE THREAD

**Issue by albatrosify** [jardenliu/XPS15-9560-Ventura#137]
You seem to have quite some knowledge about ACPI (DSDT, SSDT,..)
I've read about the benefits of openCore and read into it. However my knowledge about this is relatively close to 0.
Do you have any plans on converting your beautiful settings to openCore in near future?

**Comment by SilentSliver** [comment]
Please switch to OpenCore branch🤔
https://github.com/jardenliu/XPS15-9560-Catalina/tree/OpenCore

**Comment by albatrosify** [comment]
I am sorry. I didnt see it, and neither did I expect you would be also into opencore. Incredible. :)
