### ISSUE TITLE
DW-1820A WiFi Fix | Help needed

### ISSUE THREAD

**Issue by albatrosify** [jardenliu/XPS15-9560-Ventura#138]
So far I got everything working properly with your files.
On many pages I've read about the DW-1820A and how it's supposed to work nearly OOTB.
I swapped my card for it rebooted, it shows the WiFi Menu at the topbar but WIFI shows as "OFF".
Often the laptop will just freeze. In any case I couldnt switch on Wifi and wonder if anyone has the DW-1820A and could help?

**Comment by albatrosify** [comment]
So this can be marked as solved.
For Dell XPS 9560 it is necessary to mask some pins on the DW-1820A module.
Attached is a file from the web with red marked pins which have to be covered with tape. After that DW-1820A worked OOTB with the Clover branch from here.
![66541738-ebfc1780-eb62-11e9-837c-4db71213bdcc](https://user-images.githubusercontent.com/64252708/81733503-6b9feb00-9492-11ea-9343-19717cc9c219.png)

**Comment by albatrosify** [comment]
However I notice that WiFi after 10-15 minutes freezes and doesnt respond anymore. It is necessary to switch the WiFi off and on for it to work again.
Any ideas on that?

**Comment by albatrosify** [comment]
Seems fixed with BrcmFixUp Kext. I close this one

**Comment by albatrosify** [comment]
DW-1820A seems to work mostly.
However I experience the following issue:
At times (dont know exactly what causes this) the WiFi connection will just freeze.
The Wireless-Icon in the top bar still indicates a solid connection and shows my wifi network in the selector menu, but no data is beeing transfered. So when opening any webpage the browser wont get any answer. I tried to ping various addresses but no package beeing sent through.
With BrcmFixUp and without same problem. Anyone has an idea what to try to stabilize the WiFi ?

**Comment by intel0753** [comment]
> DW-1820A seems to work mostly.
> However I experience the following issue:
> At times (dont know exactly what causes this) the WiFi connection will just freeze.
> The Wireless-Icon in the top bar still indicates a solid connection and shows my wifi network in the selector menu, but no data is beeing transfered. So when opening any webpage the browser wont get any answer. I tried to ping various addresses but no package beeing sent through.
> With BrcmFixUp and without same problem. Anyone has an idea what to try to stabilize the WiFi ?

Have you ever tried with the correct way to inject the info of your DW1802A?
Here's a post on how to inject and drive DW1820A:
https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html

After trying this method, if the problem still exists, I suggest you should rebuild kextcache with the method in README.md.

I have a DW1830. when I upgrade to 10.15.5 I found the "WiFi application" frozen when the system started. After a reboot WiFi worked well. Then I rebuilt kextcache when WiFi worked correctly, and so far that issue never happened again. Based on this experience, I suggest you upgrade to the latest branch and rebuild kextcache.
