### ISSUE TITLE
Boot freezes on OpenCore

### ISSUE THREAD

**Issue by marcoscaco** [jardenliu/XPS15-9560-Ventura#139]
Boot freezes when I try the opencore branch, Can you provide an verbose boot config for the opencore?
I have the 9560 with i7 7700hq, 16gb of ram and 4k screen!

**Comment by SilentSliver** [comment]
Using text editor open config.plist, then finding “boot-args” key part and adding “-v” in dict sector of “boot-args”. 
If you have more questions about the oc config, please read [oc configuration](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) doc first.

**Comment by marcoscaco** [comment]
> Using text editor open config.plist, then finding “boot-args” key part and adding “-v” in dict sector of “boot-args”.
> If you have more questions about the oc config, please read [oc configuration](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) doc first.

I add -v but it does not get the verbose output

**Comment by SilentSliver** [comment]
make sure you have clean nvram after using CLOVER or changing EVERY ITEMS IN NVRAM.

**Comment by marcoscaco** [comment]
Even when i use the option "clear nvram" then try to boot it still freezes, some idea?

**Comment by SilentSliver** [comment]
It seems like a boot quirk config error in OC. Did you try the latest version on github or unlock cfg lock? 
I have use OC branch about a month and things works perfectly.

**Comment by AntSYau** [comment]
@marcoscaco Are you able to boot into OpenCore? That is, can you see disk logos at the center of the screen and a black cursor at the top-left corner?
