### ISSUE TITLE
Time won't update after sleep/wake

### ISSUE THREAD

**Issue by anthqiu** [jardenliu/XPS15-9560-Ventura#141]
For example, if I put my laptop into sleep at 8:00 and wakeup at 9:00, upon wakeup, the clock would still be 8:00, and I had to manually run `sntp -sS`.

During the whole time my laptop is connected to AC power.

My configurations:
macOS 10.15.5
CPU: i7-7700HQ
SSD: TOSHIBA 512G NVMe
Screen: 1080P
WiFi adapter: BCM94352z

**Comment by AntSYau** [comment]
I installed Windows back and found this problem also exists under Windows. Suspecting hardware mulfunction. Will reopen this issue if a problem related to this problem have been found.

I think there's something to do with the onboard CMOS battery, I'm calling dell to replace it.

**Comment by AntSYau** [comment]
I contacted Dell and this is one solution they gave me that works (reset BIOS):

1. Detach all peripherals (USB, HDMI, etc.) AND keep AC power **plugged in**
2. Turn off the system *(however for me, I have to keep the system on to successfully enter the next step)*
3. Press and hold `Power` button for 30 seconds
4. Power on the system, wait for it to reboot for several times
5. On the popup screen that reads "BIOS unset", "time/date unset" and something like that, click "`CONTINUE`". *(However, the BIOS boot sequence have been erased, so if you can't boot into Clover/OC, you will have to enter BIOS and manually add boot record)*

After these steps, the above problem should be solved.
