### ISSUE TITLE
No HDMI signal after wake from sleep

### ISSUE THREAD

**Issue by anthqiu** [jardenliu/XPS15-9560-Ventura#142]
there is a thread about fixing this on reddit: https://www.reddit.com/r/hackintosh/comments/fw16mt/fix_for_10154_hdmi_wake_from_sleep/

I haven't tested this yet, but I feel it might be helpful.

**Comment by AntSYau** [comment]
Following that thread's steps (simply adding a boot parameter) did fixed the problem for me. Submitting PR.

**Comment by jardenliu** [comment]
merged, thanks
