### ISSUE TITLE
Opencore with Mojave

### ISSUE THREAD

**Issue by ghost** [jardenliu/XPS15-9560-Ventura#151]
Is it possible to use the OpenCore brance with Mojave?  I tried and Mojave boots, but the installer doesn't show my NVMe drive.  I can't proceed any further.  Any ideas?

**Comment by DanielToubul** [comment]
hey there, have you tried to click on "show all devices" on the menu of disk utility?

**Comment by jmayniac** [comment]
Yeah I have.  Tried to use diskutil in the terminal as well, it doesn't list the ssd.
