### ISSUE TITLE
 wont connect to the iPhone hotspot

### ISSUE THREAD

**Issue by realitymolder** [jardenliu/XPS15-9560-Ventura#152]
Hey,
when using iPhone hotspot from the network menu, the connection is failing.
This has been tested on the latest OSX + latest opencore config.
That said, iMessage is working flawlessly with DW1560.
Any suggestions? 
tnx

**Comment by SilentSliver** [comment]
As far as I know, only those network card token from Apple Machine could work perfect like Mac on XPS. 
If you want use personal hotspot, you could turn off your bluetooth first then select your iphone from the network list.
