### ISSUE TITLE
Type-C to Displayport not working on latest OpenCore with Catalina 10.15.5

### ISSUE THREAD

**Issue by Flusinerd** [jardenliu/XPS15-9560-Ventura#154]
Hello,
I installed Macos with opencore on my XPS 9560 but the USB-Type-C to Displayport adapter (Wich worked with an older version of the master branch) doesn't work. I dont get any output signals.
I checked the cable and dongle and it works flawlessly on other Operating Systems.

Can someone help me or point me into the right direction?
Sincerly, Jan

**Comment by SilentSliver** [comment]
sorry for late reply. These day I will try to fix some graphics card issues which might be helpful for you.
