### ISSUE TITLE
Can we enable the Opencore Boot Chime on this machine?

### ISSUE THREAD

**Issue by marcoscaco** [jardenliu/XPS15-9560-Ventura#156]
Today the audio injection is done by the CodecComander Right?
Im trying to make the codec work with the guide but a having trouble

**Comment by SilentSliver** [comment]
in fact not. CodecComander aims to fix audio missing after wake from sleep. 
And I also have trouble at this part

**Comment by marcoscaco** [comment]
I have done, now it have the boot chime
I droped the codecComander and the ssdt
Using AppleALC id 72 and VerbStub.kext with the KNNSpeed combojack fix

**Comment by dmatora** [comment]
@marcoscaco can you share EFI?
