### ISSUE TITLE
Big Sur support

### ISSUE THREAD

**Issue by ywjung328** [jardenliu/XPS15-9560-Ventura#157]
It seems OC 0.6.0 and Lilu, WEG, etc. with new current commits seem to support Big Sur. Is there any plan to support Big Sur for 9560?

**Comment by albatrosify** [comment]
I tried to compile OC 0.6 with own compiled LILU, WEG, AppleALC etc and I can boot Catalina, but it wont transition from OpenCore to Big Sur boot. Anyone has an idea what change is necessary to start booting into big sur? I followed a video tutorial here:
https://www.youtube.com/watch?v=W91san3CXmc&list=WL&index=38&t=0s

**Comment by gps949** [comment]
> I tried to compile OC 0.6 with own compiled LILU, WEG, AppleALC etc and I can boot Catalina, but it wont transition from OpenCore to Big Sur boot. Anyone has an idea what change is necessary to start booting into big sur? I followed a video tutorial here:
> https://www.youtube.com/watch?v=W91san3CXmc

I also tried the same operation - update the OC to 0.6.0, update the LILU, WEG, VSMC, AppleALC kexts.
With adding "\System\Library\CoreServices\boot.efi" to the Misc - BlessOverride, I could see the Big Sur system's disk icon besides the install disk icon.
But it stuck at the "SMCLightSensor: alsd @ No iterator" after "IOConsoleUsers xxxxxx", seems the Intel HD360 can't be drove correctly. I heard from others that no 4K screen machine could pass this step by current.

**Comment by albatrosify** [comment]
Mh, I am stuck at this point: Any idea where I am missing something?`
Catalina just boots fine...
![image](https://user-images.githubusercontent.com/64252708/86025795-ee730a00-ba2e-11ea-8f61-76aa298248b0.png)

**Comment by albatrosify** [comment]
> > I tried to compile OC 0.6 with own compiled LILU, WEG, AppleALC etc and I can boot Catalina, but it wont transition from OpenCore to Big Sur boot. Anyone has an idea what change is necessary to start booting into big sur? I followed a video tutorial here:
> > https://www.youtube.com/watch?v=W91san3CXmc
> 
> I also tried the same operation - update the OC to 0.6.0, update the LILU, WEG, VSMC, AppleALC kexts.
> With adding "\System\Library\CoreServices\boot.efi" to the Misc - BlessOverride, I could see the Big Sur system's disk icon besides the install disk icon.
> But it stuck at the "SMCLightSensor: alsd @ No iterator" after "IOConsoleUsers xxxxxx", seems the Intel HD360 can't be drove correctly. I heard from others that no 4K screen machine could pass this step by current.

Could you kindly share your EFI? I would like to compare with mine.

**Comment by gps949** [comment]
> Mh, I am stuck at this point: Any idea where I am missing something?`
> Catalina just boots fine...
> ![image](https://user-images.githubusercontent.com/64252708/86025795-ee730a00-ba2e-11ea-8f61-76aa298248b0.png)

Well, if you stuck at the EB point as your photo show, you need to unlock the BIOS' CFG... 
Maybe you can search for how to use setup_var to set the bios cfg unlock. no business with efi.
BTW, if your 9560's bios version is 1.19.2, the CFG LOCK should be at 0x4ed. So you can use "setup_var 0x4ed 0x00" to unlock it.

**Comment by albatrosify** [comment]
Thanks for the idea with CFG Lock. I tried the quirk before, however it only seems working with Catalina. I will use an EFI Shell and set CFG Lock after updating bios

**Comment by SilentSliver** [comment]
> > I tried to compile OC 0.6 with own compiled LILU, WEG, AppleALC etc and I can boot Catalina, but it wont transition from OpenCore to Big Sur boot. Anyone has an idea what change is necessary to start booting into big sur? I followed a video tutorial here:
> > https://www.youtube.com/watch?v=W91san3CXmc
> 
> I also tried the same operation - update the OC to 0.6.0, update the LILU, WEG, VSMC, AppleALC kexts.
> With adding "\System\Library\CoreServices\boot.efi" to the Misc - BlessOverride, I could see the Big Sur system's disk icon besides the install disk icon.
> But it stuck at the "SMCLightSensor: alsd @ No iterator" after "IOConsoleUsers xxxxxx", seems the Intel HD360 can't be drove correctly. I heard from others that no 4K screen machine could pass this step by current.

the issue is only happened on laptops with 4K screen. If you want try the view you can inject platform-Id with 0x12345678

**Comment by SilentSliver** [comment]
> It seems OC 0.6.0 and Lilu, WEG, etc. with new current commits seem to support Big Sur. Is there any plan to support Big Sur for 9560?

Still have lots of issues. You can try Big Sur on a MacBook, but db1 is not fridendly to hackintosh with 4K display.

**Comment by albatrosify** [comment]
Mh. In any case could someone share an EFI that gets as far as possible?
I am still learning opencore and am still stuck at EB before actual macOS Boot. 
I would like to compare and understand why my config doesn't boot into big Sur but does into Catalina

**Comment by gps949** [comment]
> Mh. In any case could someone share an EFI that gets as far as possible?
> I am still learning opencore and am still stuck at EB before actual macOS Boot.
> I would like to compare and understand why my config doesn't boot into big Sur but does into Catalina
You can have  look at mine. I'm not sure if you can use it for installing due to I made much modification after the installation...
But it can even bring me to the lock screen & give me a glance of the desktop (then it returned to the lock screen...) after I change the platform-id to 0x12345678.

[EFI.zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4850171/EFI.zip)

**Comment by SilentSliver** [comment]
> > Mh. In any case could someone share an EFI that gets as far as possible?
> > I am still learning opencore and am still stuck at EB before actual macOS Boot.
> > I would like to compare and understand why my config doesn't boot into big Sur but does into Catalina
> 
> You can have look at mine. I'm not sure if you can use it for installing due to I made much modification after the installation...
> But it can even bring me to the lock screen & give me a glance of the desktop (then it returned to the lock screen...) after I change the platform-id to 0x12345678.
> 
> [EFI.zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4850171/EFI.zip)

If you have root user, you can login by root. After my test, it might a issue about display identify but I have no idea to fix it

**Comment by albatrosify** [comment]
With your EFI, trying to boot into installer:
![image](https://user-images.githubusercontent.com/64252708/86104655-9edc1f00-babe-11ea-8984-1c88ce49a5a6.png)
I've got an installed disk on a USB stick which when I boot it, at some points arrives to kernel panic and resets... 
In anyway this already gets further than I did. Thank you for sharing and good luck!

**Comment by YeonwooJung-postech** [comment]
I actually got my desktop working with Big Sur, so I think I can help too..? It’s tho weird that 4k display won’t work properly. I think framebuffer was not a deal when we upgrade our os, not downgrade.

**Comment by gps949** [comment]
> With your EFI, trying to boot into installer:
> ![image](https://user-images.githubusercontent.com/64252708/86104655-9edc1f00-babe-11ea-8984-1c88ce49a5a6.png)
> I've got an installed disk on a USB stick which when I boot it, at some points arrives to kernel panic and resets...
> In anyway this already gets further than I did. Thank you for sharing and good luck!


I didn't meet this. I've no idea whether it caused by USB stick installation. Mine is on the internal disk.
Good luck for both of us :)

**Comment by albatrosify** [comment]
This is actually when booting the installer from USB Stick. 
I have another partition with an installed macOS (of an original macbook) which during boot has a kernel panic and then resets.

So with your EFI I am unable to boot into installer and neither boot into the installed macOS (of macbook pro)

**Comment by albatrosify** [comment]
Booting into installer is still not possible but I could finally boot the pre-installed big sur.
![image](https://user-images.githubusercontent.com/64252708/86156355-1aad8a00-bb06-11ea-8663-9b7f95d23edf.png)
I also had to set platform-id to something else, becuase boot would hang on gpu init.
seems ok so far, most things work.

**Comment by YeonwooJung-postech** [comment]
> > With your EFI, trying to boot into installer:
> > ![image](https://user-images.githubusercontent.com/64252708/86104655-9edc1f00-babe-11ea-8984-1c88ce49a5a6.png)
> > I've got an installed disk on a USB stick which when I boot it, at some points arrives to kernel panic and resets...
> > In anyway this already gets further than I did. Thank you for sharing and good luck!
> 
> I didn't meet this. I've no idea whether it caused by USB stick installation. Mine is on the internal disk.
> Good luck for both of us :)

If you don't mind, can you tell me how did you got into the verbose mode? I do have -v on boot-args, but it's not working...

**Comment by albatrosify** [comment]
What you could try is to add boot-args to NVRAM->DELETE.
As far as I understood it will overwrite the boot-args Everytime then when opencore loads.
But research first - I am really no expert of opencore.

**Comment by SilentSliver** [comment]
> Booting into installer is still not possible but I could finally boot the pre-installed big sur.
> ![image](https://user-images.githubusercontent.com/64252708/86156355-1aad8a00-bb06-11ea-8663-9b7f95d23edf.png)
> I also had to set platform-id to something else, becuase boot would hang on gpu init.
> seems ok so far, most things work.

It’s a issue about edid and screen checksum. Due to hackintosh’s edid and checksum have missing some bytes , bigsur could not identify 4K screen on laptops normally. To boot system normally you need inject edid and checksum which has been fixed. 
A new issue that screen frequency couldn’t work at 60Hz.

**Comment by gps949** [comment]
> > Booting into installer is still not possible but I could finally boot the pre-installed big sur.
> > ![image](https://user-images.githubusercontent.com/64252708/86156355-1aad8a00-bb06-11ea-8663-9b7f95d23edf.png)
> > I also had to set platform-id to something else, becuase boot would hang on gpu init.
> > seems ok so far, most things work.
> 
> It’s a issue about edid and screen checksum. Due to hackintosh’s edid and checksum have missing some bytes , bigsur could not identify 4K screen on laptops normally. To boot system normally you need inject edid and checksum which has been fixed.
> A new issue that screen frequency couldn’t work at 60Hz.

Could you offer an EDID which may light the internal 4K monitor? I've tried several but no one fit and I'm still using an external monitor through hdmi...

**Comment by SilentSliver** [comment]
> > > Booting into installer is still not possible but I could finally boot the pre-installed big sur.
> > > ![image](https://user-images.githubusercontent.com/64252708/86156355-1aad8a00-bb06-11ea-8663-9b7f95d23edf.png)
> > > I also had to set platform-id to something else, becuase boot would hang on gpu init.
> > > seems ok so far, most things work.
> > 
> > 
> > It’s a issue about edid and screen checksum. Due to hackintosh’s edid and checksum have missing some bytes , bigsur could not identify 4K screen on laptops normally. To boot system normally you need inject edid and checksum which has been fixed.
> > A new issue that screen frequency couldn’t work at 60Hz.
> 
> Could you offer an EDID which may light the internal 4K monitor? I've tried several but no one fit and I'm still using an external monitor through hdmi...

The only one must be your own screen edid and checksum(after fix). I provide this idea (the display issue must be caused by edid ) to a friend who uses 7590. He find out this way. I will try to ask him how to fix this.

**Comment by gps949** [comment]
> > > > Booting into installer is still not possible but I could finally boot the pre-installed big sur.
> > > > ![image](https://user-images.githubusercontent.com/64252708/86156355-1aad8a00-bb06-11ea-8663-9b7f95d23edf.png)
> > > > I also had to set platform-id to something else, becuase boot would hang on gpu init.
> > > > seems ok so far, most things work.
> > > 
> > > 
> > > It’s a issue about edid and screen checksum. Due to hackintosh’s edid and checksum have missing some bytes , bigsur could not identify 4K screen on laptops normally. To boot system normally you need inject edid and checksum which has been fixed.
> > > A new issue that screen frequency couldn’t work at 60Hz.
> > 
> > 
> > Could you offer an EDID which may light the internal 4K monitor? I've tried several but no one fit and I'm still using an external monitor through hdmi...
> 
> The only one must be your own screen edid and checksum(after fix). I provide this idea (the display issue must be caused by edid ) to a friend who uses 7590. He find out this way. I will try to ask him how to fix this.

Finally got an EDID can light up my internal monitor:
00FFFFFF FFFFFF00 4D108D14 00000000 051C0104 A5221378 0EDF19A9 5334BC25 0C515400 00000101 01010101 01010101 01010101 010150D0 00A0F070 3E803020 350058C2 1000001A A6A600A0 F0703E80 30203500 58C21000 00180000 00FD0038 4C1E5311 000A2020 20202020 000000FC 00436F6C 6F72204C 43440A20 20200093

But there seems still two issues:
1. the frequency is 48Hz.
2. when plug in HDMI cable, it will reboot...

**Comment by dmatora** [comment]
> Finally got an EDID can light up my internal monitor:

Are you using Clover or OpenCore? How do you inject it?
Can you share your EFI?

**Comment by dmatora** [comment]
>Booting into installer is still not possible but I could finally boot the pre-installed big sur.

I managed to boot installer and wipe/install system using open core, but without graphics acceleration installer crashes after reboot same as installed system when you open control center

Tried Injecting (using both Clover and OpenCore) provided EDID and EDID I exported in Catalina using SwitchResX, and still getting black screen :(

**Comment by SilentSliver** [comment]
> > > > > Booting into installer is still not possible but I could finally boot the pre-installed big sur.
> > > > > ![image](https://user-images.githubusercontent.com/64252708/86156355-1aad8a00-bb06-11ea-8663-9b7f95d23edf.png)
> > > > > I also had to set platform-id to something else, becuase boot would hang on gpu init.
> > > > > seems ok so far, most things work.
> > > > 
> > > > 
> > > > It’s a issue about edid and screen checksum. Due to hackintosh’s edid and checksum have missing some bytes , bigsur could not identify 4K screen on laptops normally. To boot system normally you need inject edid and checksum which has been fixed.
> > > > A new issue that screen frequency couldn’t work at 60Hz.
> > > 
> > > 
> > > Could you offer an EDID which may light the internal 4K monitor? I've tried several but no one fit and I'm still using an external monitor through hdmi...
> > 
> > 
> > The only one must be your own screen edid and checksum(after fix). I provide this idea (the display issue must be caused by edid ) to a friend who uses 7590. He find out this way. I will try to ask him how to fix this.
> 
> Finally got an EDID can light up my internal monitor:
> 00FFFFFF FFFFFF00 4D108D14 00000000 051C0104 A5221378 0EDF19A9 5334BC25 0C515400 00000101 01010101 01010101 01010101 010150D0 00A0F070 3E803020 350058C2 1000001A A6A600A0 F0703E80 30203500 58C21000 00180000 00FD0038 4C1E5311 000A2020 20202020 000000FC 00436F6C 6F72204C 43440A20 20200093
> 
> But there seems still two issues:
> 
> 1. the frequency is 48Hz.
> 2. when plug in HDMI cable, it will reboot...
Try This
[0712-SilverSliver-OC-Test-BigSur(4K@48Hz) .zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4907280/0712-SilverSliver-OC-Test-BigSur.4K%4048Hz.zip)

**Comment by SilentSliver** [comment]
[0712-SilentSliver-OC-Test-BigSur(4K@48Hz) .zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4907292/0712-SilverSliver-OC-Test-BigSur.4K%4048Hz.zip)

It could be install and boot system, but 4k Display screen will work at 48Hz. 
All you need to do is same as ReadME.md in OpenCore branch.

**Comment by dmatora** [comment]
This doesn't boot, doesn't even have drivers folder.
I took devices section from config, and it framebuffer-con0-alldata + framebuffer-con0-enable got me external monitor working, like Clover does, but unlike Clover when external monitor is attached it will crash after a few seconds.
Btw, where did you get the value for framebuffer-con0-alldata?

**Comment by SilentSliver** [comment]
My mistake, Try this
[0712-SilentSliver-OC-Test-BigSur(4K@48Hz).zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4907898/0712-SilentSliver-OC-Test-BigSur.4K%4048Hz.zip)
Framebuffer-con0-data has generated at 10.15. Black Screen is a EDID issue. You need add `AAPL00,override-no-connect` at `PciRoot(0x0)/Pci(0x2,0x0)` in `Device Propertries` but not Framebuffer-con0 to fix your laptop screen. External Display still have some error

**Comment by dmatora** [comment]
@SilentSliver it's exactly the same folder. just with drives added.
It didn't refuse to boot because drivers were missing, I can add those myself
it just fails to initialise (not just Big Sur but older systems as well)

![telegram-cloud-photo-size-2-5213283565503098552-y](https://user-images.githubusercontent.com/647062/87246129-d306f680-c453-11ea-8fef-3809433943dc.jpg)

**Comment by SilentSliver** [comment]
Using oc please read the readme of oc branch first. You need UNLOCK CFG LOCK FIRST or enable SOME QUIRKS in KERNEL PART. Did you check this part in readme?

**Comment by dmatora** [comment]
> enable SOME QUIRKS in KERNEL

@SilentSliver I thought i have copied quirks settings from working config, but i guess i've missed a checkbox. I've tried it again and this time it booted and internal monitor is finally working! Thanks man! Plus booting with external monitor connected doesn't crash it anymore! (but hotplug does)

> when plug in HDMI cable, it will reboot...

@gps949 I've added a patch to fix crash on external monitor hotplug, here you go

[config.plist.zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4909117/config.plist.zip)

Another issue is my external 4k monitor is detected as 1080p (don't really care about it at the moment, just wanted to test touch screen on internal monitor in Big Sur)

**Comment by gps949** [comment]
> > enable SOME QUIRKS in KERNEL
> 
> @SilentSliver I thought i have copied quirks settings from working config, but i guess i've missed a checkbox. I've tried it again and this time it booted and internal monitor is finally working! Thanks man! Plus booting with external monitor connected doesn't crash it anymore! (but hotplug does)
> 
> > when plug in HDMI cable, it will reboot...
> 
> @gps949 I've added a patch to fix crash on external monitor hotplug, here you go
> 
> [config.plist.zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4909117/config.plist.zip)
> 
> Another issue is my external 4k monitor is detected as 1080p (don't really care about it at the moment, just wanted to test touch screen on internal monitor in Big Sur)


Thank you for your help! With your patch, the HDMI monitor hotplug won't crash now!


Below is the list of current problems:
1. The monitor can only work @48Hz;
2. Seems the 'Sidecar' can't work now... (before fix the HDMI issue it can work normally. I've no idea which change caused this)
3. No VM software can work well... (This may be Big Sur's compatible issue)
PD can run a WIN system with some keys no responding ("1", "2", "T", "Y"). VMWare will report "mem out of usage" even though I set the VM only 2GB mem. VirtualBox can't startup a VM...

**Comment by dmatora** [comment]
> * Seems the 'Sidecar' can't work now... (before fix the HDMI issue it can work normally. I've no idea which change caused this)

You can try disabling some display connections in Device Properties and hopefully find a combination that allows both to be working.

**Comment by SilentSliver** [comment]
> > * Seems the 'Sidecar' can't work now... (before fix the HDMI issue it can work normally. I've no idea which change caused this)
> 
> @gps949 All i did to fix hotplug is added missing display connections in Device Properties (copied the fix from Hackintool). You can try disabling some of those connections and hopefully find a combination that allows both to be working.

All Data should contain ALL Connections which I have defined. I think kernel panic when plug out HDMI might be some thing wrong with kernel cache?

**Comment by SilentSliver** [comment]
I have redo a new efi to fix some errors about HDMI, and sidecar works fine with me
[0714-SilentSliver-OpenCore-Test(HDMI-Fix).zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/4916687/0714-SilentSliver-OpenCore-Test.HDMI-Fix.zip)

**Comment by ultratiem** [comment]
> Well, if you stuck at the EB point as your photo show, you need to unlock the BIOS' CFG...
> Maybe you can search for how to use setup_var to set the bios cfg unlock. no business with efi.
> BTW, if your 9560's bios version is 1.19.2, the CFG LOCK should be at 0x4ed. So you can use "setup_var 0x4ed 0x00" to unlock it.

Do NOT use setup_var. Repeat, do not use setup_var.

The correct method is to use setup_var_3.

**Comment by SilentSliver** [comment]
> > Well, if you stuck at the EB point as your photo show, you need to unlock the BIOS' CFG...
> 
> > Maybe you can search for how to use setup_var to set the bios cfg unlock. no business with efi.
> 
> > BTW, if your 9560's bios version is 1.19.2, the CFG LOCK should be at 0x4ed. So you can use "setup_var 0x4ed 0x00" to unlock it.
> 
> 
> 
> Do NOT use setup_var. Repeat, do not use setup_var.
> 
> 
> 
> The correct method is to use setup_var_3.

Thanks for your comment. Could you tell us more details?

**Comment by ultratiem** [comment]
https://github.com/datasone/grub-mod-setup_var

Read Patch section.

**Comment by YeonwooJung-postech** [comment]
Is there anyone with good news about display issue? I'm planning to move to bs if there's any solution I can get 60hz, but I cannot find any solution, I mean, not even a same problem reported on the other devices :(

**Comment by SilentSliver** [comment]
> Is there anyone with good news about display issue? I'm planning to move to bs if there's any solution I can get 60hz, but I cannot find any solution, I mean, not even a same problem reported on the other devices :(

As I know, most laptop with 4K display screen will have this problem except XPS 13 (the detail of model i forgot), even 9570 and so on. 
In a Chinese hackintosh forum there are lots of different laptops reported they have this [issue](http://bbs.pcbeta.com/viewthread-1862446-1-4.html)

**Comment by YeonwooJung-postech** [comment]
> > Is there anyone with good news about display issue? I'm planning to move to bs if there's any solution I can get 60hz, but I cannot find any solution, I mean, not even a same problem reported on the other devices :(
> 
> As I know, most laptop with 4K display screen will have this problem except XPS 13 (the detail of model i forgot), even 9570 and so on.
> In a Chinese hackintosh forum there are lots of different laptops reported they have this [issue](http://bbs.pcbeta.com/viewthread-1862446-1-4.html)

Thanks for your info! I’m seriously curious why there’s no thread handling about this issue in English-based forum :(

**Comment by SilentSliver** [comment]
> > > Is there anyone with good news about display issue? I'm planning to move to bs if there's any solution I can get 60hz, but I cannot find any solution, I mean, not even a same problem reported on the other devices :(
> > 
> > 
> > As I know, most laptop with 4K display screen will have this problem except XPS 13 (the detail of model i forgot), even 9570 and so on.
> > In a Chinese hackintosh forum there are lots of different laptops reported they have this [issue](http://bbs.pcbeta.com/viewthread-1862446-1-4.html)
> 
> Thanks for your info! I’m seriously curious why there’s no thread handling about this issue in English-based forum :(

Sorry but I don’t know either, so I also don’t know how to fix it with no idea.

**Comment by sammy1881** [comment]
I can't get WiFi/Bluetooth to work. I'm using DW1560. Anyone had better luck with Wifi?

**Comment by ywjung328** [comment]
> I can't get WiFi/Bluetooth to work. I'm using DW1560. Anyone had better luck with Wifi?

Faced the same issue with mine too. One weird thing is that my desktop with dw1560 has zero problem on BS. Even instant wifi works with dw1560...

**Comment by ywjung328** [comment]
> > > > Is there anyone with good news about display issue? I'm planning to move to bs if there's any solution I can get 60hz, but I cannot find any solution, I mean, not even a same problem reported on the other devices :(
> > > 
> > > 
> > > As I know, most laptop with 4K display screen will have this problem except XPS 13 (the detail of model i forgot), even 9570 and so on.
> > > In a Chinese hackintosh forum there are lots of different laptops reported they have this [issue](http://bbs.pcbeta.com/viewthread-1862446-1-4.html)
> > 
> > 
> > Thanks for your info! I’m seriously curious why there’s no thread handling about this issue in English-based forum :(
> 
> Sorry but I don’t know either, so I also don’t know how to fix it with no idea.

Thanks for the reply! I opened a thread at Korean community. I hope we can find a solution sooner or later :)

**Comment by dmatora** [comment]
I'm using BCM94360NG and it works without issues. It uses Apple chip and doesn't need any kexts/patches to work

**Comment by ywjung328** [comment]
> I'm using BCM94360NG and it works without issues. It uses Apple chip and doesn't need any kexts/patches to work

Isn’t that the native one? I ordered the one too, for the instant wifi XD

**Comment by gps949** [comment]
> > I can't get WiFi/Bluetooth to work. I'm using DW1560. Anyone had better luck with Wifi?
> 
> Faced the same issue with mine too. One weird thing is that my desktop with dw1560 has zero problem on BS. Even instant wifi works with dw1560...

try to use the newest version AirportBrcmFixup.kext (need to remove the 4360 plugin inside it) and add its NIC plugin into the kernel in config.plist

**Comment by sammy1881** [comment]
> > > I can't get WiFi/Bluetooth to work. I'm using DW1560. Anyone had better luck with Wifi?
> > 
> > 
> > Faced the same issue with mine too. One weird thing is that my desktop with dw1560 has zero problem on BS. Even instant wifi works with dw1560...
> 
> try to use the newest version AirportBrcmFixup.kext (need to remove the 4360 plugin inside it) and add its NIC plugin into the kernel in config.plist

This has done the trick for me. Thanks @gps949 :)

**Comment by ywjung328** [comment]
> > > > Is there anyone with good news about display issue? I'm planning to move to bs if there's any solution I can get 60hz, but I cannot find any solution, I mean, not even a same problem reported on the other devices :(
> > > 
> > > 
> > > As I know, most laptop with 4K display screen will have this problem except XPS 13 (the detail of model i forgot), even 9570 and so on.
> > > In a Chinese hackintosh forum there are lots of different laptops reported they have this [issue](http://bbs.pcbeta.com/viewthread-1862446-1-4.html)
> > 
> > 
> > Thanks for your info! I’m seriously curious why there’s no thread handling about this issue in English-based forum :(
> 
> Sorry but I don’t know either, so I also don’t know how to fix it with no idea.

It seems my EDID and yours are quite different... I thought the same display components should have same EDID but was I wrong?

Plus! It seems now the latest Lilu and SMC related kexts commits not requiring vsmcgen=1 or extra arguments for booting the device without prelinked kernel! Yeah!

**Comment by LeLunZ** [comment]
Nah, every Display has its own EDID which gets „inserted“ into the display while manufacturing.


With Linux you can easily grab your edid. 
There are a lot of Tools out there.

**Comment by ywjung328** [comment]
> Nah, every Display has its own EDID which gets „inserted“ into the display while manufacturing.
> 
> With Linux you can easily grab your edid.
> There are a lot of Tools out there.

Nah, forgive my ignorance XD I extracted mine with ioreg on Catalina. I didn't know that mine had its own specific EDID since it worked well with his display's EDID..

**Comment by stereolith** [comment]
In [this comment](https://github.com/acidanthera/bugtracker/issues/1057#issuecomment-671813154) a user shared a python3 script to extract the EDID and generate the checksum-ed version.
Works flawlessly with my 9560 4K, I can boot into Catalina and Big Sur with it.

**Comment by marcoscaco** [comment]
Some News on BigSur support?

**Comment by SilentSliver** [comment]
> Some News on BigSur support?

Nope

**Comment by ywjung328** [comment]
> Some News on BigSur support?

The only one left so far is the display issue, but that is because of the change / missing of Core Display Framework on Big Sur, which should be handled by kext developers. So we should wait for their support :(

**Comment by SilentSliver** [comment]
> > Some News on BigSur support?
> 
> The only one left so far is the display issue, but that is because of the change / missing of Core Display Framework on Big Sur, which should be handled by kext developers. So we should wait for their support :(

Might be some hard operation. I think it will be unable to fix before Big Sur release.

**Comment by ywjung328** [comment]
> > > Some News on BigSur support?
> > 
> > 
> > The only one left so far is the display issue, but that is because of the change / missing of Core Display Framework on Big Sur, which should be handled by kext developers. So we should wait for their support :(
> 
> Might be some hard operation. I think it will be unable to fix before Big Sur release.

I hope Apple fixes the problem on the later official release... I found some apps using CDF are all facing the problem.

**Comment by ywjung328** [comment]
@SilentSliver It seems you've blocked the EDID injection part in the recent commit. Is there any reason for that? Should I enable it when installing BS?

**Comment by ywjung328** [comment]
> @SilentSliver It seems you've blocked the EDID injection part in the recent commit. Is there any reason for that? Should I enable it when installing BS?

Yes we needed, for sure.

**Comment by SilentSliver** [comment]
> > @SilentSliver It seems you've blocked the EDID injection part in the recent commit. Is there any reason for that? Should I enable it when installing BS?
> 
> Yes we needed, for sure.

Injecting this edid will cause black screen under 1080p display. So if you need we need enable it by ourselves.

**Comment by albatrosify** [comment]
Just a quick feedback:
with latest OC branch from here, and custom EDID I am having no problems so far in Big Sur, except for 48HZ on internal display.
I can use usb-c connected 4K display and have 60Hz there.
So far no complains. I hope we can find a fix for internal 48HZ->60HZ.

**Comment by adityahota** [comment]
The issue relies on Lilu's userspace patching working with Big Sur, as this enables CoreDisplayFixup (now part of WhateverGreen). CDF enables 4K internal panels to operate at 60 Hz, so we need to see if Lilu will be able to support userspace patching on BS. Until then, no 60 Hz for us (I am using an XPS 9570 UHD display).

**Comment by DanielToubul** [comment]
OpenCore 0.6.3 supports now BigSur RC which is great :) 
do we want to create a new git for BigSur? as it is stated Catalina. 
Or it will be updated?

**Comment by CryptoNeverSleeps** [comment]
This gives hope that we may soon finally have a fix for XPS 7590 OLED.... Thanks everyone...

**Comment by CryptoNeverSleeps** [comment]
https://github.com/gorquan/OC-XPS-7590/issues/5

**Comment by ywjung328** [comment]
> OpenCore 0.6.3 supports now BigSur RC which is great :)
> do we want to create a new git for BigSur? as it is stated Catalina.
> Or it will be updated?

This repo works ok with Big Sur.

**Comment by albatrosify** [comment]
Anyone try Big Sur RC with latest opencore branch from this repo here?
I am only having a black screen. Previous versions of Big Sur seemed to work fine.
(Of course I added my Display EDID and removed the # infront of the key in config.plist)

**Comment by ywjung328** [comment]
> Anyone try Big Sur RC with latest opencore branch from this repo here?
> 
> I am only having a black screen. Previous versions of Big Sur seemed to work fine.
> 
> (Of course I added my Display EDID and removed the # infront of the key in config.plist)
> 
> 

Wait till it boots. It will work after rebooting for few times, and some of them will take a while.

**Comment by albatrosify** [comment]
I am on the setup screen. When I connect a display via usb-c i can see it. but internal display will be stuck on loading screen meanwhile

**Comment by madicrossing** [comment]
Here's my current EFI for my 9560 running Big Sur with OC 0.6.3. It took me a very long time to get it set up and running, but my 4k display works fine (albeit at 48Hz due to broken Lilu userspace patches that have yet to be fixed and may never be). Don't know if it'll work to install Big Sur as I've edited it pretty heavily since initial install, but people still having issues could try it and see if it works!
[EFI.zip](https://github.com/jardenliu/XPS15-9560-Catalina/files/5541757/EFI.zip)

**Comment by albatrosify** [comment]
Very nice madicrossing. With your EFI my BigSur works perfect (except for 48Hz of course).
What I noticed, is that DRM Content (e.g prime video) will not play. Might this be connected to the issue with lilu userspace patching?

**Comment by madicrossing** [comment]
Yes, DRM and the 48Hz issue are (as far as I know) both due to Lilu userspace patching that needs updating. Unfortunately, due to changes made in Big Sur, some Lilu devs have said that they might drop support for userspace patching entirely. For now, I just use Firefox for DRM content that won't play in Safari.

**Comment by LeLunZ** [comment]
> Yes, DRM and the 48Hz issue are (as far as I know) both due to Lilu userspace patching that needs updating. Unfortunately, due to changes made in Big Sur, some Lilu devs have said that they might drop support for userspace patching entirely. For now, I just use Firefox for DRM content that won't play in Safari.

How did DRM Content work before? I never got It to work on Catalina and Mojave... I thought IGPU only doesn't work.
Firefox uses the same as google chrome for drm content. I think its google's Widevine CDM.

**Comment by ywjung328** [comment]
## UPDATE

I know it's closed issue and I already sold my xps and got mbp 15 2016, but I believe this news can help you.

https://github.com/acidanthera/WhateverGreen/commit/978cb8c7a744ac189074225fd8eb2f16feb5a4c0

According to the latest commit on WEB, now we can raise max pixel clock, which means we can get 4k 60hz!! Yay!!

**Comment by jardenliu** [comment]
@ywjung328 please follow the change log . 5 day ago, fix  the pixel clock . f391880d7dc6bf743d977654190c71718eef2f1e
