### ISSUE TITLE
Screen freezed after sleep

### ISSUE THREAD

**Issue by lawman21c** [jardenliu/XPS15-9560-Ventura#158]
My laptop is i5 cpu with 4k screen,ax200 wifi adapter.
I am using  your opencore efi file.Everything works fine except one issue .The screen freezed,all blacked after the system sleep.And the system seems to be hung up,so I have to cold reboot the system.

**Comment by SilentSliver** [comment]
All things have been tested on my 4K i7 with BRCM DW1830. I think you can try one quirk at “Kernel->quirks->powertimeoutkernelpanic” and enable it. 
I think it also might be a display issue which the gpu or screen has some thing wrong at wake part after sleep part. If the method below has no help about you question, you need to check your config about gpu and display.
