### ISSUE TITLE
10.15.6 OTA upgrading Error Happened，Help Needed

### ISSUE THREAD

**Issue by CloudLasting** [jardenliu/XPS15-9560-Ventura#159]
Has anyone encountered this problem when 9560(10.15.5) ota upgrading with current opencore efi configuration？
![image](https://user-images.githubusercontent.com/11511934/88364710-57dc0380-cdb6-11ea-9b30-01bc45d0f0ca.png)
I have checked a lot of blogs and others information, but failed to solve this problem.

**Comment by SilentSliver** [comment]
Please use opencore currently. For more details please read [this](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf). 
These drivers on picture you post(from Clover?) are absolutely NOT from opencore branch of this repo.

**Comment by CloudLasting** [comment]
> Please use opencore currently. For more details please read [this](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf).
> These drivers on picture you post(from Clover?) are absolutely NOT from opencore branch of this repo.

I am indeed using the current opencore efi configuration,I don’t know whether anyone has successfully upgraded 10.15.6.
