### ISSUE TITLE
extremly Slow SSD Write speed compared to Read

### ISSUE THREAD

**Issue by mangohenry** [jardenliu/XPS15-9560-Ventura#160]
<img width="703" alt="Screen Shot 2020-08-03 at 1 00 04 pm" src="https://user-images.githubusercontent.com/41656321/89142009-90839600-d589-11ea-9ebf-6a48620b4358.png">

SSD set to ACHI mode in BIOS
  TRIM Support:	Yes
  Model:	KXG50ZNV512G NVMe TOSHIBA 512GB

**Comment by SilentSliver** [comment]
It might be low pci speed which will cause this. There is [a guide](https://www.win-raid.com/t6941f16-Guide-Increasing-NVME-and-eGPU-OPI-Link-Speed-to-GT-s-on-Dell-laptops.html#msg118705) if you want to try to unlock full performance of your ssd.
