### ISSUE TITLE
Trackpad Gestures

### ISSUE THREAD

**Issue by LeLunZ** [jardenliu/XPS15-9560-Ventura#161]
The trackpad gestures doesn't seem to work anymore in the master branch.
I have cleared the kextcache and the problem still exists.

After testing I found that: 
2 Finger gestures are working (scrolling, safari back/forward)
3 Fingere Gestures now work with 5 Fingers...

**Comment by SilentSliver** [comment]
delete voodooinput in voodoops2 might be solve it

**Comment by LeLunZ** [comment]
Thx for the tip. That solved the whole problem.
Where do you got this info from?

**Comment by SilentSliver** [comment]
> Thx for the help. That solved the whole problem.
> Where do you got this info from?

 It might be an issue about version, I guess.

**Comment by LeLunZ** [comment]
Will write an issue at Voodoo 👍 thx
