### ISSUE TITLE
OC 0.6.0 is not working? 

### ISSUE THREAD

**Issue by realitymolder** [jardenliu/XPS15-9560-Ventura#162]
Hey there, I have update the OC folder as usual like in older versions, but this time it seems that the version is not working well.
I keep getting a halt in the boot. 
Thanks in advance! 
![IMG_0951](https://user-images.githubusercontent.com/26459151/89708514-a970ba80-d980-11ea-92ca-b519600cf2fc.jpg)

**Comment by SilentSliver** [comment]
Are you using a 4K display internal screen? Try to add -cdfon at boot-args in config.plist

**Comment by DanielToubul** [comment]
Thanks! It worked and so far, everything is working perfectly.
