### ISSUE TITLE
Trackpad sometimes not working

### ISSUE THREAD

**Issue by albatrosify** [jardenliu/XPS15-9560-Ventura#163]
Hello all.

I am having the following issue since a while (across multiple versions of OC).
Randomly after booting into macOS my Trackpad wont work. Keyboard works fine but I can not move the cursor except when plugging in a USB Mouse or Bluetooth Mouse.

However the trackpad is dead. Anyone with the same problem or any idea how to fix it?
Many thanks 👍

**Comment by LeLunZ** [comment]
Try `sudo kextcache -i /`
And a reboot.

**Comment by albatrosify** [comment]
I tried this after updating to the latest changes in OC branch. It didnt work. I will try again and see...
Thanks anyway 👍
