### ISSUE TITLE
OCS: No schema for Boot at 1 index, context <root>!

### ISSUE THREAD

**Issue by silentbanana50** [jardenliu/XPS15-9560-Ventura#164]
Getting this error when trying to boot using open core usb

**Comment by ywjung328** [comment]
Do your config.plist and OC version match?

**Comment by silentbanana50** [comment]
How do I check?

**Comment by silentbanana50** [comment]
Fixed: I plugged the config.plist into open ore sanity checker and performed all of the recommended changes. It boots now.
