### ISSUE TITLE
I use XPS9560 1080P OPENCORE, always error (中文)

### ISSUE THREAD

**Issue by jasjang** [jardenliu/XPS15-9560-Ventura#165]
謝謝您的教學
我用的是1080p機種有修改uiscale了
使用opencore安裝時按照您的教學
開機boot時 選擇opencore之後 就黑畫面不動了
想請教有沒有什麼方法

**Comment by SilentSliver** [comment]
你可以試著先不修改UIScale，避免因為Config.plist格式錯誤而不能進入OpenCore Bootloader階段。
如果還是不可以的話，可以參考[OpenCore手冊](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf)修改`Misc->Debug->Display Level`以對其進行調試。

**Comment by jasjang** [comment]
我有試著不修改 還是黑畫面
另外有試著設定DisplayLevel 但還是沒有任何資訊
我的是1080p沒有觸控螢幕的版本
在請指教了 謝謝

**Comment by SilentSliver** [comment]
黑畫面之前有任何的Log或者信息顯示麼？
如果實在不行的話，我這裡提供一個我當前正在用的[OpenCore EFI](https://github.com/jardenliu/XPS15-9560-Catalina/files/5147785/OC.zip)看能不能幫助你進入系統，但前提是你至少已經按照ReadME設置過BIOS並解鎖CFG Lock了。

**Comment by jasjang** [comment]
先謝謝分享 
目前用這版本還是黑畫面 
我先試著解鎖CFG Lock
謝謝

**Comment by arachnophilia1997** [comment]
for 1080p, i think he have to remove <key>#AAPL00,override-no-connect</key>.
