### ISSUE TITLE
WIFI & Bluetooth Issues

### ISSUE THREAD

**Issue by ionas-dev** [jardenliu/XPS15-9560-Ventura#167]
When I use WIFI or Bluetooth by itself it works just fine, but when I'm connected to a bluetooth device the wifi doesn't work at all. I use the DW1830, but the third antenna isn't connected currently. Is this the problem?

**Comment by SilentSliver** [comment]
You can connect the third antenna first then test stability of WiFi and Bluetooth

**Comment by Jonass-K** [comment]
That’s what it was. Thanks
