### ISSUE TITLE
How to enable HDR on 9560?

### ISSUE THREAD

**Issue by albatrosify** [jardenliu/XPS15-9560-Ventura#168]
Hello all,

I am using a DELL U2720Q HDR Monitor. And I would really like to use the HDR capability with the Hackintosh.
As far as I know the corresponding MacBook Model we use does not support HDR.

Would you recommend just to use/switch to a newer Model Identifier to enable HDR from system or is there any other way to do it more elegant?

Many thanks in advance!

**Comment by SilentSliver** [comment]
Try this [one](https://github.com/jardenliu/XPS15-9560-Catalina/files/5224312/0915-SilentSliver-OpenCore-Test-USBPort.zip) which would fix USB errors when switch Model. 
These day I will commit these new hot patches to fix the things you said.

**Comment by albatrosify** [comment]
Thank you. Funny enough I am unable to change the system identifier / serial.
I have edited your OC and inserted new identifier with new serial nbr etc but it wont show after a restart.
I am using the correct OC BootLoader (the one you provided), but no matter what I do, the system always shows the old serial and model identifier. In any case. It is not too urgent and I can wait until you push this to OC Branch

**Comment by SilentSliver** [comment]
> Thank you. Funny enough I am unable to change the system identifier / serial.
> I have edited your OC and inserted new identifier with new serial nbr etc but it wont show after a restart.
> I am using the correct OC BootLoader (the one you provided), but no matter what I do, the system always shows the old serial and model identifier. In any case. It is not too urgent and I can wait until you push this to OC Branch

Try to reset nvram to fix this？

**Comment by albatrosify** [comment]
I tried with CMD+OPT+P+R (am not 100% sure if I pressed the correct buttons) but I tried all combinations. Unfortunately boot picker doesnt show Clear NVRAM option. How can I make it visible?

**Comment by SilentSliver** [comment]
only space

**Comment by Zacharybinx34** [comment]
> Try this [one](https://github.com/jardenliu/XPS15-9560-Catalina/files/5224312/0915-SilentSliver-OpenCore-Test-USBPort.zip) which would fix USB errors when switch Model.
> These day I will commit these new hot patches to fix the things you said.

I have this one working, but how do I scrub your other boot options from it that were for your system?

**Comment by SilentSliver** [comment]
> > Try this [one](https://github.com/jardenliu/XPS15-9560-Catalina/files/5224312/0915-SilentSliver-OpenCore-Test-USBPort.zip) which would fix USB errors when switch Model.
> > These day I will commit these new hot patches to fix the things you said.
> 
> I have this one working, but how do I scrub your other boot options from it that were for your system?

Delete them at `Misc` part

**Comment by Zacharybinx34** [comment]
> > > Try this [one](https://github.com/jardenliu/XPS15-9560-Catalina/files/5224312/0915-SilentSliver-OpenCore-Test-USBPort.zip) which would fix USB errors when switch Model.
> > > These day I will commit these new hot patches to fix the things you said.
> > 
> > 
> > I have this one working, but how do I scrub your other boot options from it that were for your system?
> 
> Delete them at `Misc` part

Then how can I add my own windows installation to it? 
1 HD - 2 partitions

Thanks!

**Comment by SilentSliver** [comment]
Blessoverride could provide windows boot loader option with some functions about boot camp (might be?). For more details you can read the guild from Acidanthera (forgive my poor English and I didn’t read this part )

**Comment by Zacharybinx34** [comment]
> Blessoverride could provide windows boot loader option with some functions about boot camp (might be?). For more details you can read the guild from Acidanthera (forgive my poor English and I didn’t read this part )

Ok thank you. 

One other issue though, I have the DW1560 wifi + bluetooth card, but only the wifi works. How can I make this work with your setup?

**Comment by SilentSliver** [comment]
> > Blessoverride could provide windows boot loader option with some functions about boot camp (might be?). For more details you can read the guild from Acidanthera (forgive my poor English and I didn’t read this part )
> 
> Ok thank you.
> 
> One other issue though, I have the DW1560 wifi + bluetooth card, but only the wifi works. How can I make this work with your setup?

Check whether the USB port has been defined under macOS, and did bt work normally before? Try to shutdown your system above 10 seconds then boot it and check your bt

**Comment by Zacharybinx34** [comment]
> > > Blessoverride could provide windows boot loader option with some functions about boot camp (might be?). For more details you can read the guild from Acidanthera (forgive my poor English and I didn’t read this part )
> > 
> > 
> > Ok thank you.
> > One other issue though, I have the DW1560 wifi + bluetooth card, but only the wifi works. How can I make this work with your setup?
> 
> Check whether the USB port has been defined under macOS, and did bt work normally before? Try to shutdown your system above 10 seconds then boot it and check your bt

How do I check that?
I just got this card, so I haven't gotten bluetooth working yet.

**Comment by Zacharybinx34** [comment]
> > > Blessoverride could provide windows boot loader option with some functions about boot camp (might be?). For more details you can read the guild from Acidanthera (forgive my poor English and I didn’t read this part )
> > 
> > 
> > Ok thank you.
> > One other issue though, I have the DW1560 wifi + bluetooth card, but only the wifi works. How can I make this work with your setup?
> 
> Check whether the USB port has been defined under macOS, and did bt work normally before? Try to shutdown your system above 10 seconds then boot it and check your bt

This is from my bios showing the working windows entree. 
https://media.discordapp.net/attachments/696301098075422741/755661316827643974/image0.jpg?width=1504&height=1128

This is my OpenCore Entry:
https://media.discordapp.net/attachments/696301098075422741/755661317649727548/image1.jpg?width=1504&height=1128

I have bless override pointing to the following, though it doesn't work. 
\EFI\Microsoft\Boot\bootmgfw.efi

This is the manual entry I tried editing from yours to get it working, but it doesn't. 

PciRoot(0x0)/Pci(0x17,0x0)/Sata(0x0,0x0)/NVMe(0x1,66-35-10-00-03-0D-08-00)/HD(1,GPT,07AB9B8E-0DBB-4A51-A249-19148A7BBA2E,0x6,0x12FFA)/\EFI\Microsoft\Boot\bootmgfw.efi

Any ideas would be GREATLY appreciated!

**Comment by SilentSliver** [comment]
> > > > Blessoverride could provide windows boot loader option with some functions about boot camp (might be?). For more details you can read the guild from Acidanthera (forgive my poor English and I didn’t read this part )
> > > 
> > > 
> > > Ok thank you.
> > > One other issue though, I have the DW1560 wifi + bluetooth card, but only the wifi works. How can I make this work with your setup?
> > 
> > 
> > Check whether the USB port has been defined under macOS, and did bt work normally before? Try to shutdown your system above 10 seconds then boot it and check your bt
> 
> How do I check that?
> I just got this card, so I haven't gotten bluetooth working yet.

You can use `Hackintool` to check the ports. 
Also most Bluetooth cards are  ram usb devices. It means that their firmware will stored at memory of system. To reload their firmware you need to shutdown your system to turnoff your memory on motherboard then boot up to re-inject firmware.

**Comment by Zacharybinx34** [comment]
> > > > > Blessoverride could provide windows boot loader option with some functions about boot camp (might be?). For more details you can read the guild from Acidanthera (forgive my poor English and I didn’t read this part )
> > > > 
> > > > 
> > > > Ok thank you.
> > > > One other issue though, I have the DW1560 wifi + bluetooth card, but only the wifi works. How can I make this work with your setup?
> > > 
> > > 
> > > Check whether the USB port has been defined under macOS, and did bt work normally before? Try to shutdown your system above 10 seconds then boot it and check your bt
> > 
> > 
> > How do I check that?
> > I just got this card, so I haven't gotten bluetooth working yet.
> 
> You can use `Hackintool` to check the ports.
> Also most Bluetooth cards are ram usb devices. It means that their firmware will stored at memory of system. To reload their firmware you need to shutdown your system to turnoff your memory on motherboard then boot up to re-inject firmware.

I turned off the laptop for about 30 seconds, but it still doesn't work. It works fine in Windows 10 though. 
What can I do to get it working properly? I really need Bluetooth. 
Thanks!

**Comment by SilentSliver** [comment]
> > > > > > Blessoverride could provide windows boot loader option with some functions about boot camp (might be?). For more details you can read the guild from Acidanthera (forgive my poor English and I didn’t read this part )
> > > > > 
> > > > > 
> > > > > Ok thank you.
> > > > > One other issue though, I have the DW1560 wifi + bluetooth card, but only the wifi works. How can I make this work with your setup?
> > > > 
> > > > 
> > > > Check whether the USB port has been defined under macOS, and did bt work normally before? Try to shutdown your system above 10 seconds then boot it and check your bt
> > > 
> > > 
> > > How do I check that?
> > > I just got this card, so I haven't gotten bluetooth working yet.
> > 
> > 
> > You can use `Hackintool` to check the ports.
> > Also most Bluetooth cards are ram usb devices. It means that their firmware will stored at memory of system. To reload their firmware you need to shutdown your system to turnoff your memory on motherboard then boot up to re-inject firmware.
> 
> I turned off the laptop for about 30 seconds, but it still doesn't work. It works fine in Windows 10 though.
> It's weird, cuz it shows the bluetooth device properly within OS X, I can turn it off and on, but it doesn't find any devices to connect to.
> What can I do to get it working properly? I really need Bluetooth.
> Thanks!

If you have Bluetooth panel in system preferences, it means you have injected your Bluetooth card firmware. So which branch do you use now? Clover or OC? Do you check your be-connected device and are they at Bluetooth pairing view?

**Comment by SilentSliver** [comment]
I’m using wf 1000xm3 and my Bluetooth works well. You need provide me more details about your Bluetooth devices and their status

**Comment by Zacharybinx34** [comment]
> I’m using wf 1000xm3 and my Bluetooth works well. You need provide me more details about your Bluetooth devices and their status

Hello, thank you for the resply!
"I **am using the M.2 NGFF WiFi Network Card Broadcom BCM94360NG BCM94352Z DW1560 BT4.0 LAN**"

OS X Catalina (using your Open Core build) detects the card, I can turn it off and on, however, when scanning for devices it shows nothing. It's blank and no available bluetooth devices ever show up there. They show on my phone right next to it, but not on the Hackintosh. 

Thank you!

**Comment by SilentSliver** [comment]
> > I’m using wf 1000xm3 and my Bluetooth works well. You need provide me more details about your Bluetooth devices and their status
> 
> Hello, thank you for the resply!
> "I **am using the M.2 NGFF WiFi Network Card Broadcom BCM94360NG BCM94352Z DW1560 BT4.0 LAN**"
> 
> OS X Catalina (using your Open Core build) detects the card, I can turn it off and on, however, when scanning for devices it shows nothing. It's blank and no available bluetooth devices ever show up there. They show on my phone right next to it, but not on the Hackintosh.
> 
> Thank you!

Emmm... a strange issue. Do you check it under windows? Will devices show at bt devices list?
If not it might be a issue about firmware. You could try to remove boot-args about bt in nvram and test the stability.

**Comment by SilentSliver** [comment]
Solved this
bluetooth issue has been created a new thread

**Comment by albatrosify** [comment]
Is the fix for HDR already commited to OC branch?

**Comment by ywjung328** [comment]
> Is the fix for HDR already commited to OC branch?

I have 4k model and the internal display's HDR has been working OOB with this repo. How did you connect your monitor with your laptop?

**Comment by albatrosify** [comment]
I have a Dell U2720Q connected via USB-C.
I did not try with the internal display. I will check. With the external display it doesn't show the option for usb c

**Comment by albatrosify** [comment]
So, I just downloaded the latest OC branch, changes only my serial number, etc.
But I am not seeing the option to enable HDR in display settings.
Furthermore in regards to Apple Website, the model we use is not capable of HDR. 
Do you use the "MacBook Pro (15-inch, 2017)" model?

**Comment by ywjung328** [comment]
> So, I just downloaded the latest OC branch, changes only my serial number, etc.
> 
> But I am not seeing the option to enable HDR in display settings.
> 
> Furthermore in regards to Apple Website, the model we use is not capable of HDR. 
> 
> Do you use the "MacBook Pro (15-inch, 2017)" model?

So through the type c port, is your monitor connected as HDMI or DP? Smbios model doesn't matter about HDR. 2017 models aren't that old.
