### ISSUE TITLE
Mac crashes

### ISSUE THREAD

**Issue by ionas-dev** [jardenliu/XPS15-9560-Ventura#170]
I don't know if this is a general problem of macOS or if its a Hackintosh problem, but my dell crashes nowadays very often.
The report is: 

>panic(cpu 4 caller 0xffffff800f8469aa): Kernel trap at 0xffffff7f9219af91, type 13=general protection, registers:
>
>CR0: 0x000000008001003b, CR2: 0x00007fb9050ce710, CR3: 0x000000001c3be000, CR4: 0x00000000003626e0
>RAX: 0xffffff8050e0fd80, RBX: 0x0000000000000001, RCX: 0xc0ffee558bc9efe6, RDX: 0x0000000001000000
>RSP: 0xffffff81f87ebd80, RBP: 0xffffff81f87ebdc0, RSI: 0xffffff8050e0fd80, RDI: 0xffffff8038d56820
>R8:  0x0000000000000005, R9:  0x0000000000000004, R10: 0x0000000000000001, R11: 0x0000000000000005
>R12: 0xffffff804df39100, R13: 0x000000000000525a, R14: 0x000000000000525a, R15: 0xffffff8043a66400
>RFL: 0x0000000000010282, RIP: 0xffffff7f9219af91, CS:  0x0000000000000008, SS:  0x0000000000000010
>Fault CR2: 0x00007fb9050ce710, Error code: 0x0000000000000000, Fault CPU: 0x4, PL: 0, VF: 0
>
>Backtrace (CPU 4), Frame : Return Address
>0xffffff800f553220 : 0xffffff800f71a65d mach_kernel : _handle_debugger_trap + 0x49d
>0xffffff800f553270 : 0xffffff800f854a75 mach_kernel : _kdp_i386_trap + 0x155
>0xffffff800f5532b0 : 0xffffff800f8465fe mach_kernel : _kernel_trap + 0x4ee
>0xffffff800f553300 : 0xffffff800f6c0a40 mach_kernel : _return_from_trap + 0xe0
>0xffffff800f553320 : 0xffffff800f719d27 mach_kernel : _DebuggerTrapWithState + 0x17
>0xffffff800f553420 : 0xffffff800f71a117 mach_kernel : _panic_trap_to_debugger + 0x227
>0xffffff800f553470 : 0xffffff800fec1abc mach_kernel : _panic + 0x54
>0xffffff800f5534e0 : 0xffffff800f8469aa mach_kernel : _sync_iss_to_iks + 0x2aa
>0xffffff800f553660 : 0xffffff800f8466a8 mach_kernel : _kernel_trap + 0x598
>0xffffff800f5536b0 : 0xffffff800f6c0a40 mach_kernel : _return_from_trap + 0xe0
>0xffffff800f5536d0 : 0xffffff7f9219af91 com.sinet3k.Sinetek-rtsx : __ZN12Sinetek_rtsx15rtsx_pci_attachEv + 0x219
>0xffffff81f87ebdc0 : 0xffffff7f9219abce com.sinet3k.Sinetek-rtsx : __ZN12Sinetek_rtsx5startEP9IOService + 0xb4
>0xffffff81f87ebde0 : 0xffffff800fe075c6 mach_kernel : __ZN9IOService14startCandidateEPS_ + 0xf6
>0xffffff81f87ebe40 : 0xffffff800fe07101 mach_kernel : __ZN9IOService15probeCandidatesEP12OSOrderedSet + 0xad1
>0xffffff81f87ebef0 : 0xffffff800fe0649e mach_kernel : __ZN9IOService14doServiceMatchEj + 0x2de
>0xffffff81f87ebf50 : 0xffffff800fe08c56 mach_kernel : __ZN15_IOConfigThread4mainEPvi + 0x186
>0xffffff81f87ebfa0 : 0xffffff800f6c013e mach_kernel : _call_continuation + 0x2e
>      Kernel Extensions in backtrace:
>         com.sinet3k.Sinetek-rtsx(7.0)[A1A75920-8823-3148-966D-41250B251F6C]@0xffffff7f9218f000->0xffffff7f921d0fff
>            dependency: com.apple.iokit.IOPCIFamily(2.9)[DF219CC1-366A-31FC-B8ED->17C584BA2549]@0xffffff7f90301000
>           dependency: com.apple.iokit.IOStorageFamily(2.1)[3581A46A-F3F3-3CE7-BA52->7046E8D66C32]@0xffffff7f90065000
>
>BSD process name corresponding to current thread: kernel_task
>Boot args: -lilubetaall vsmcgen=1 darkwake=0 -rtsx_no_adma keepsyms=1 agdpmod=vit9696 bpr_probedelay=100 >bpr_initialdelay=300 bpr_postresetdelay=300 -igfxtypec -disablegfxfirmware 
>
>Mac OS version:
>19G2021
>
>Kernel version:
>Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
>Kernel UUID: 1D3A0F3D-D908-397B-BD16-8F48C0823A2E
>Kernel slide:     0x000000000f400000
>Kernel text base: 0xffffff800f600000
>__HIB  text base: 0xffffff800f500000
>System model name: MacBookPro14,3 (Mac-551B86E5744E2388)
>System shutdown begun: NO
>Panic diags file available: YES (0x0)
>
>System uptime in nanoseconds: 83156577121662
>last loaded kext at 83156472554172: >!UAudio	323.4 (addr 0xffffff7f93659000, size 434176)
>last unloaded kext at 83104799689358: ru.joedm.SMCSuperIO	1.1.6 (addr 0xffffff7f921d1000, size 49152)
>loaded kexts:
>
>

**Comment by SilentSliver** [comment]
Delete Sinetec-rtsx, I will try to solve it these days.
