### ISSUE TITLE
DW1560 shows up, but bluetooth finds no devices

### ISSUE THREAD

**Issue by Zacharybinx34** [jardenliu/XPS15-9560-Ventura#171]
Device shows, wifi works, but bluetooth finds nothing on scan. 

https://media.discordapp.net/attachments/696301098075422741/758045356385894400/unknown.png?width=659&height=1341

**Comment by SilentSliver** [comment]
Did you test your 1560 under windows? If DW1560 works perfectly at windows, I think it might be caused by firmware.

**Comment by Zacharybinx34** [comment]
> Did you test your 1560 under windows? If DW1560 works perfectly at windows, I think it might be caused by firmware.

It works fine under Windows. How do I fix it for OS X?

**Comment by LeLunZ** [comment]
Did you also copy the kext from [here](https://github.com/jardenliu/XPS15-9560-Catalina/tree/master/Post-install/non-DW1830BT(非DW1830使用))? 

@SilentSliver you updated the aml file sometime ago. Does the aml file in the Post-install folder also need an update?
And should we also copy the kext?

**Comment by tri-ler** [comment]
You can try setting the max kernel as I described #186 to see if it helps. I have the same wireless card as you and had issues as well.

**Comment by Zacharybinx34** [comment]
> You can try setting the max kernel as I described #186 to see if it helps. I have the same wireless card as you and had issues as well.

Mine was already set to that. What else can I do?
