### ISSUE TITLE
DW1560 doesn´t connect to a Ipad or Iphone hotspot

### ISSUE THREAD

**Issue by hamburgerjung1887** [jardenliu/XPS15-9560-Ventura#172]
Hello,
my DW1560 does not connect to my hotspot Neither to the Ipad, nor to the Iphone. Under Windows10 it works fine. What can be the reason?

**Comment by ywjung328** [comment]
1. Turn off the bluetooth so that they won't use airport service. DW1560 has somehow compatible with macs, but not 100%.
2. Install Big Sur. IDK why, but after installing Big Sur on my hackintoshed desktop w/ DW1560, instant hotspot works with no problem.
