### ISSUE TITLE
OpenCore: freeze on apple logo while installing

### ISSUE THREAD

**Issue by dan-leech** [jardenliu/XPS15-9560-Ventura#173]
I have strange behavior with OpenCore.

My differences:
1. 1080p display
2. Killer wifi card
3. I left enabled sd card reader in BIOS
4. My BIOS version 1.20.0
5. OS X Catalina 10.15.7

In config I only change UIScale to 1.
Sometimes I see the picker screen, sometimes only the black. I've tried to debug and the last string in logs is about waiting 10000 microseconds before start. (it means all is ok.)

When I start the installation I see only apple logo without loading all the time. I've tried to wait several minutes, nothing has changed.

Do you know how to debug installing process or what could be wrong?
With Clover I see loading but it ends with crossed out circle.

**Comment by dan-leech** [comment]
The issue was that I had to use a plist editor instead a text editor.

**Comment by dan-leech** [comment]
I've figured out how to enable verbose mode and in 10.15.7 installer it shows:
![P_20201011_105355_vHDR_Auto](https://user-images.githubusercontent.com/6331634/95674870-bea1d980-0bbb-11eb-9518-a9938658f110.jpg)
after ~10 seconds:
![P_20201011_105431_vHDR_Auto](https://user-images.githubusercontent.com/6331634/95674873-c5305100-0bbb-11eb-9d22-edf554621c16.jpg)

I think it's USBMSC Identifier (non-unique) issue that related to USB devices attaching. I've tried to solve this myself but not succeed.
1. I used this advises https://github.com/jardenliu/XPS15-9560-Catalina/issues/118#issuecomment-613547735
2. I tried to disable Thunderbolt in BIOS
3. I used USB2 flash card. I use USB3Flash usually.

**Comment by arachnophilia1997** [comment]
I was bootin in to black screen on 1080p display, but the HDMI out worked so used that. 

I'm not sure, but I believe that the NO AAPL key in config.plist Device Oroperties is the EDID injection for 4k display.  The laptop display worked after I removed it.
