### ISSUE TITLE
OpenCore: audio headsets solution

### ISSUE THREAD

**Issue by dan-leech** [jardenliu/XPS15-9560-Ventura#174]
I've tried to execute `ALC298PluginFix` but it does not work for me with headsets.
I've found [ComboJack](https://github.com/hackintosh-stuff/ComboJack/blob/master/ComboJack_Installer) maybe it would help somebody.
You need just run `install.sh` to make it works permanently or `ComboJack` to test it.

**Comment by albatrosify** [comment]
For me it was sufficient to use the provided ALC Plugin fix in OC branch. Make sure to translate the files, as one is to INSTALL the fix and the other to UNINSTALL.

**Comment by jardenliu** [comment]
2820486c0cc252a21c17706c9527fc347779e8c3 ALC298PluginFix work for Big Sur
