### ISSUE TITLE
Occasionally trackpad does not work

### ISSUE THREAD

**Issue by albatrosify** [jardenliu/XPS15-9560-Ventura#176]
Hello @all,

every now and then, when I boot into macOS, the trackpad wont work.
I tried "kextcache -i /" several times, but normally it is enough to just reboot.
However sometimes a few reboots are necessary for the trackpad to work again.
In windows I do never have problems with the trackpad so I guess it's not a hardware issue.

Anyone having an idea how to find out what is causing the intermittend operation of the trackpad?

**Comment by ywjung328** [comment]
Have you ever updated the whole EFI partition and I2C kexts? Also, I think we have to know whether you're using OC or Clover.

**Comment by albatrosify** [comment]
I should be somewhat close to the latest OC branch commit. I do have kextupdater tool on mac mac which tells me that a few kexts are outdated. Do you recommend to just update them? I shouldnt be needing to change anything in OC config for that after replacing the outdated kexts no?

**Comment by dan-leech** [comment]
I've updated them and all is running well.
You can just try with booting from usb first.

**Comment by albatrosify** [comment]
I didnt have the trackpad issues since a while now. Seems like it is fixed with updating.
