### ISSUE TITLE
Latests commits doesn't work for 10.15

### ISSUE THREAD

**Issue by LeLunZ** [jardenliu/XPS15-9560-Ventura#177]
After the last few commit it seems like a few things are broken.

- wlan doesnt work anymore with DW1560
- if wlan is on. The mouse hangs every few seconds
- read and write speeds are at the lowest 0,044 mb/s (took me like 20 minutes to copy the old Clover folder into Efi partition)

@SilentSliver is it still compatible with 10.15 or only with BigSur?

**Comment by albatrosify** [comment]
I am not having any of those problems with the current OC Branch.
Did you try to switch to OC from Clover?

**Comment by LeLunZ** [comment]
I am on clover branch. But I will switch to OC :) just hadn’t time for it!
