### ISSUE TITLE
ALC298PluginFix does not work in Catalina or Big Sur (OpenCore 6.3)

### ISSUE THREAD

**Issue by wenxue68** [jardenliu/XPS15-9560-Ventura#180]
When I first updated OpenCore to 6.3 a while ago, the headset plugin stopped working. I have upgraded the system to big sur but the issue still persists. I have tried numerous fixes, including copying the fix files, but the headphones still provide no audio output

**Comment by nmnobre** [comment]
Duplicate of #179. Follow the instructions outlined there.

**Comment by wenxue68** [comment]
With today's latest config.plist , I can't get into MacOS Big Sur

**Comment by jardenliu** [comment]
@wenxue68 headphones fixed by latest post_install/alc298pluginfix

**Comment by jardenliu** [comment]
0.6.3 not support yet
