### ISSUE TITLE
kernel output tons of AMFI: <key> <something> not found

### ISSUE THREAD

**Issue by dixyes** [jardenliu/XPS15-9560-Ventura#181]
Using my os updated from Catalina, with -v option, bootlog gives tons of AMFI warinings,this seems also affecting boot speed.
我用我从Catalina升上来的系统 加了-v选项 启动日志里全是amfi key xx找不到 好像还影响启动速度 不知道啥情况

**Comment by wenxue68** [comment]
After I upgraded to OC6.4, I found that the battery didn't display properly
