### ISSUE TITLE
Audio not working after update from Catalina to Big Sur

### ISSUE THREAD

**Issue by Saidou83** [jardenliu/XPS15-9560-Ventura#183]
Hi,

Just updated from Catalina to Big Sur. (with latest master build)
Everything seems OK, but I can't get my audio to work in Big Sur.

_My config: Intel I7 / 16G / Samsung 970 EVO 1TB / DW1830 / 4K(touch)_

I first ran "install双击自动卸载.command" (to remove) and after a reboot I ran "install.sh"

This doesn't fix the issue.

Any suggestions?

Thanks a lot!

**Comment by yxrdydh** [comment]
You can modify the config.plist file.
Try enable ACPIBatteryManager and disable SMCBatteryManager kext to fix the audio.
Then your audio will be ok but the trackpad setting is missing.
You can disable ACPIBatteryManager and enable SMCBatteryManager kext again to fix the trackpad setting. 
Then I got both audio and trackpad settings working. I don't know what happened with the config file.

**Comment by Saidou83** [comment]
Thanks for your suggestion.
I enabled **ACPIBatteryManager** and disabled **SMCBatteryManager** in my _config.plist_ and then rebooted, but that doesn't make a difference.
Trackpad is still working, but audio is still not available...

![image](https://user-images.githubusercontent.com/3101877/101679565-cf59b900-3a5f-11eb-8d00-9f4441299ee1.png)
![image](https://user-images.githubusercontent.com/3101877/101679774-1182fa80-3a60-11eb-92db-adc5b06be6d2.png)

**Comment by yxrdydh** [comment]
try my OC files. 
[OC.zip](https://github.com/jardenliu/XPS15-9560-BigSur/files/5669197/OC.zip)

**Comment by jardenliu** [comment]
fix it by latest release
