### ISSUE TITLE
USB-C Fix

### ISSUE THREAD

**Issue by Zacharybinx34** [jardenliu/XPS15-9560-Ventura#184]
Just passing this along for a reference, but this guy seems to have USB-C working!

https://www.tonymacx86.com/threads/guide-dell-xps-9560-big-sur-opencore.307163/page-7

**Comment by jardenliu** [comment]
No valuable clue were found from this page

**Comment by Zacharybinx34** [comment]
Did you look at his setup files? Just passing it on to try and help - seems he has everything but Nvidia card working.

**Comment by jardenliu** [comment]
No new features found from her installation file. and USB-C always works. 
Hopefully, can you point out what should be fixed?

**Comment by Jonass-K** [comment]
usb-c hotplug doesn't work with my xps
