### ISSUE TITLE
USB errors or loads to black screen

### ISSUE THREAD

**Issue by Zacharybinx34** [jardenliu/XPS15-9560-Ventura#185]
When I try to launch the USB installer for Big Sur, I get an unreadable error message. But then when I enable -v or even just AppleDebug or ApplePanic to true, the USB won't load the boot options. It goes right to an all black screen.

**Comment by jardenliu** [comment]
1080P screen?

**Comment by Zacharybinx34** [comment]
> 1080P screen?

4k screen/touch, with i5 cpu. It's super odd, I can't get it to boot even the Open Core EFI boot menu. It gives some error about the boot chime size not matching, and then goes to an all black screen.

**Comment by abimaelv** [comment]
I had the same issue in my 4K XPS, I fixed it by copying Bootx64.efi file to OC folder. Don't know why it worked but it did.
