### ISSUE TITLE
About hotpatch

### ISSUE THREAD

**Issue by Mateo1234454545** [jardenliu/XPS15-9560-Ventura#187]
Can you tell me what this section of ssdt-adp1.aml does ?

Device (_SB.PCI0.LPCB.ECDV.CHRG)
        {
            Name (_HID, "DELLBBB1")  // _HID: Hardware ID
            Method (_STA, 0)  // _STA: Status
            {
                Return (0x0F)
            }
        }

Thank you.

**Comment by jardenliu** [comment]
Power fix,  cause AppleACPIACAdapter to be loaded

**Comment by Mateo1234454545** [comment]
Yes, that is what adpi1 does.
But the section above adds a CHRG device. Do you know what is needed for?
