### ISSUE TITLE
WiFi card won't work on BigSur?

### ISSUE THREAD

**Issue by realitymolder** [jardenliu/XPS15-9560-Ventura#190]
Hey guys, I'm using the DW1560 if I'm correct or 1830... not sure 100% because I have both on different systems (sorry) can I check that on the OS? 
Anyhow, the WiFi card is not working anymore, in Catalina the WiFi was working flawlessly  - plug and play.

Thanks in advance.

**Comment by TommyChongg** [comment]
me too, and I use the old config file, which worked somehow.

**Comment by realitymolder** [comment]
> me too, and I use the old config file, which worked somehow.

so probably some issue with bigsur..

**Comment by hjhgitw** [comment]
I would suggest to buy (and you never think about wifi airplay or bluetooth)

https://www.ebay.de/itm/Laptop-Wireless-Wifi-Card-NGFF-M-2-BCM94360NG-Hackintosh-wifi-Card-MacOS-Windows/203042809834?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649

Native Support NO other kext or any patching needed
Supports Apple Bluetooth keyboard in BIOS/UEFI or Bootloader
NO spare keyboard needed to be able to get to BIOS/UEFI or in Bootloader
Support hackintosh/Mac OS Continuity & handoff AirDrop
Support Apple Bluetooth Keyboard, Magic Mouse, Magic Trackpad
Free driver for Mac OS,Hackintosh system(plug and play),If you need the driver for Windows system,please contact our customer service

**Comment by realitymolder** [comment]
> I would suggest to buy (and you never think about wifi airplay or bluetooth)
> 
> https://www.ebay.de/itm/Laptop-Wireless-Wifi-Card-NGFF-M-2-BCM94360NG-Hackintosh-wifi-Card-MacOS-Windows/203042809834?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2057872.m2749.l2649
> 
> Native Support NO other kext or any patching needed
> Supports Apple Bluetooth keyboard in BIOS/UEFI or Bootloader
> NO spare keyboard needed to be able to get to BIOS/UEFI or in Bootloader
> Support hackintosh/Mac OS Continuity & handoff AirDrop
> Support Apple Bluetooth Keyboard, Magic Mouse, Magic Trackpad
> Free driver for Mac OS,Hackintosh system(plug and play),If you need the driver for Windows system,please contact our customer service

hey man we are using a plug&play card like this one

**Comment by nmnobre** [comment]
See #196.

**Comment by realitymolder** [comment]
> See #196.

I did, it actually broke my usb ethernet adapter. and still, the wifi didn't work with that. 
Any suggestions?

**Comment by realitymolder** [comment]
@jardenliu  hey, the topic is still up - shouldn't be closed.
thanks

**Comment by nmnobre** [comment]
> > See #196.
> 
> 
> 
> I did, it actually broke my usb ethernet adapter. and still, the wifi didn't work with that. 
> 
> Any suggestions? 
> 
> 

Did you find out what WiFi card your system really has? Try [DPCIManager](https://sourceforge.net/projects/dpcimanager/). It used to work back in the day. You can also just fire up a GNU/Linux live image and run `lspci`.

**Comment by realitymolder** [comment]
> > > See #196.
> > 
> > 
> > 
> > I did, it actually broke my usb ethernet adapter. and still, the wifi didn't work with that. 
> > 
> > Any suggestions? 
> > 
> > 
> 
> Did you find out what WiFi card your system really has? Try [DPCIManager](https://sourceforge.net/projects/dpcimanager/). It used to work back in the day. You can also just fire up a GNU/Linux live image and run `lspci`.

Hey yes, it is DW1560 BCM94352Z NGFF M.2 WiFi WLAN Fit Bluetooth 4.0 802.11ac 867Mbps BCM94352
The link is here: 
https://he.aliexpress.com/item/32862859069.html?spm=a2g0s.9042311.0.0.3cf34c4dJRUqT7

**Comment by realitymolder** [comment]
Maybe i should just disable these Kexts and it will work? It was plug and play after all..
