### ISSUE TITLE
opencore 引导BigSur安装错误问题请教

### ISSUE THREAD

**Issue by pbeenig** [jardenliu/XPS15-9560-Ventura#193]
本子配置信息：XPS15 9560  
CPU：Intel I7 7700HQ
内存：海力士 32G(16*2) 2400MHz DDR4
硬盘：东芝 NVMe 1024G
WIFI 网卡： DW1820A
屏幕分辨率：4K 触控屏

@jardenliu 你好，最近我用黑果小兵提供的的最新BigSur镜写入U盘后，EFI替换成了你提供的EFI，并打上了先前在用的三码，成功进入opencore引导。选择 macOS Big Sur  Install后进入Logo界面， 但是之后就一直卡住在logo界面， 通过开启-v 跑码后看到一些错误信息， 但是找了很多帖子也没有研究出哪里出了问题，想请教一下你，有没有应对的方式:

![WechatIMG41](https://user-images.githubusercontent.com/15244970/108661510-f411e880-7506-11eb-9315-89331e5a05ae.jpeg)

macOS Big Sur 11.2.1 20D75 Installer for OpenCore 0.6.6 and CLOVER 5129 and PE三EFI分区原版镜像

**Comment by jardenliu** [comment]
解锁CFG lock

**Comment by pbeenig** [comment]
> 解锁CFG锁

嗯？ 在这之前我已经用opencore 安装成功了  Catalina，并且正在用作主力机在用

**Comment by jardenliu** [comment]
先解锁呗

**Comment by pbeenig** [comment]
> 先解锁呗

嗯嗯， 多谢老哥

**Comment by eeezae** [comment]
你好，我也是用的这个镜像，请问为什么连OC引导安装界面都进不去呀，我是把小兵Clover里面EFI中的内容全部替换为OC的了，但是启动显示StartImage failed -- unsupported。机器的硬件配置和你完全一致，bios配置也都已经修改了（之前也用的Catalina）

**Comment by jardenliu** [comment]
检查镜像md5

**Comment by eeezae** [comment]
> 检查镜像md5

检查了和小兵提供的是一致的

**Comment by eeezae** [comment]
我现在正准备下载一个11.1的镜像再试一下
