### ISSUE TITLE
HDMI output does not support 4k@60hz

### ISSUE THREAD

**Issue by kabychow** [jardenliu/XPS15-9560-Ventura#194]
<img width="768" alt="Screenshot 2021-03-28 at 12 13 54 AM" src="https://user-images.githubusercontent.com/4311327/112745090-a6036100-8f5a-11eb-9529-cd2915b6cacd.png">

How can I get 60hz? Thanks!

**Comment by Artemis-Hunt** [comment]
XPS 9560 has a HDMI 1.4 port, which only does 4K30 maximum. This is true even in Windows. To get full 4K60 you need to connect via a USB-C to DP cable or a Thunderbolt hub with DP.

**Comment by jardenliu** [comment]
@Artemis-Hunt He's right
