### ISSUE TITLE
DW1560驱动和引导问题

### ISSUE THREAD

**Issue by iPermanent** [jardenliu/XPS15-9560-Ventura#196]
使用了这个efi以后，感觉引导进系统比较随机，因为我是通过移动硬盘做成启动盘安装的，导致安装好以后经常没法进去系统，有时候连上移动硬盘就好了，有时候连上也不行，很随机的黑屏。另外就是无线网卡DW1560没有办法驱动成功，一直处于无网状态

**Comment by nmnobre** [comment]
The DW1560 network card stopped working due to commit 2337b985155fa976278985ce39f0bacd5744e698, which reverted the changes in commit 79d4b0229939f98af720fd685c6c0600f8471c59. The injector plugins in `AirportBrcmFixup.kext` need to be active.

Don't forget to move `SSDT-USBP.aml` and `USBPorts.kext` under `Post-install` to their rightful places as detailed in the readme.

**Comment by jardenliu** [comment]
[config.plist.zip](https://github.com/jardenliu/XPS15-9560-BigSur/files/6388977/config.plist.zip)
试试这个 try it

**Comment by iPermanent** [comment]
> [config.plist.zip](https://github.com/jardenliu/XPS15-9560-BigSur/files/6388977/config.plist.zip)
> 试试这个 try it

感谢，我晚上回去试一下，只用改plist就行了吗

**Comment by jardenliu** [comment]
@iPermanent 是的

**Comment by iPermanent** [comment]
> @iPermanent 是的

昨天试过了问题更严重了，一直重启，在config.plist里加了boot arguments -v 也没起作用，之前在mojave的时候我装完以后好像是因为有部分uefi是识别默认在移动硬盘导致没法启动我拷过去就好了但是这次看了下移动硬盘的efi目录下没有文件，另外我现在是装完了系统以后，efi下面还有几个关于apple的，苹果系统自动生成的几个目录，感觉是得删除掉才对

**Comment by jardenliu** [comment]
我下周整体升级一遍吧

**Comment by jardenliu** [comment]
@iPermanent 试下今天的最近提交的

**Comment by iPermanent** [comment]
> @iPermanent 试下今天的最近提交的

好的，晚上回去我试一下，感谢分享

**Comment by iPermanent** [comment]
> @iPermanent 试下今天的最近提交的
试了下，引导完全正常了，就是开机显示启动项的时候有点抖动，不过网卡依旧无法驱动起来

**Comment by nmnobre** [comment]
[config.plist.zip](https://github.com/jardenliu/XPS15-9560-BigSur/files/6446547/config.plist.zip)

That's the configuration file I use for an i7-7700HQ, 1080p, and DW1560 equipped machine.

**Comment by iPermanent** [comment]
> [config.plist.zip](https://github.com/jardenliu/XPS15-9560-BigSur/files/6446547/config.plist.zip)
> 
> That's the configuration file I use for an i7-7700HQ, 1080p, and DW1560 equipped machine.

Thank you but my machine is 4k with dw1560，how should I modidy this file to adapt display

**Comment by nmnobre** [comment]
Ah I see... anyway, I think your issue can be solved by using the `config.plist` in this repo (don't use mine) and setting the max kernel version to `19.9.9` in line 740.
 ![image](https://user-images.githubusercontent.com/25757109/117557025-e3353580-b066-11eb-848a-9c6713d8d9bb.jpeg)

**Comment by iPermanent** [comment]
> Ah I see... anyway, I think your issue can be solved by using the `config.plist` in this repo (don't use mine) and setting the max kernel version to `19.9.9` in line 740.
> ![image](https://user-images.githubusercontent.com/25757109/117557025-e3353580-b066-11eb-848a-9c6713d8d9bb.jpeg)

great! it resolve my problem, thank you
