### ISSUE TITLE
i7-7700 CPU被限制到 800MHZ

### ISSUE THREAD

**Issue by Nanrer** [jardenliu/XPS15-9560-Ventura#197]
多档变频不正常，起个后台服务就卡得不行.检测频率只有700-800Mhz档位

**Comment by jardenliu** [comment]
重新生成`CPUFriendDataProvider.kext`，替换旧的

**Comment by Nanrer** [comment]
发现是静电导致cpu降频,针对xps-9560 扣电池放电解决
