### ISSUE TITLE
Bluetooth Offline

### ISSUE THREAD

**Issue by CloudLasting** [jardenliu/XPS15-9560-Ventura#198]
Bluetooth is often offline. How can I get Bluetooth back online. Mine is DW1560.
![image](https://user-images.githubusercontent.com/11511934/117389955-d9ed8100-af1f-11eb-8004-642334d90d75.png)
Bigsur 11.2.3

**Comment by jardenliu** [comment]
try the latest release

**Comment by CloudLasting** [comment]
> try the latest release

My OC is already the latest,  the BT is useless no matter how to restart it.

**Comment by jardenliu** [comment]
Sometime I try to fix it. but I dont have DW 1560. So I can‘t test it
