### ISSUE TITLE
icloud无法联系服务器，已替换三码。

### ISSUE THREAD

**Issue by JOJOESCape** [jardenliu/XPS15-9560-Ventura#199]
icloud无法联系服务器，已替换三码。
appstore可以登录。
用的tl-wn725n的usb网卡。
（另外开机或重启会时不时会黑屏，出不来引导画面，不是100%发生，挺奇怪的…

**Comment by jardenliu** [comment]
内建网卡

**Comment by jardenliu** [comment]
更换网卡或者添加 `NullEthernet.kext` 驱动
