### ISSUE TITLE
WiFi card is not working in the current config

### ISSUE THREAD

**Issue by realitymolder** [jardenliu/XPS15-9560-Ventura#203]
Hey I'm rocking the dw1560 on the XPS 9560, the current config wont show me any wifi card that is connected. seems like the plist is not  supporting that card? 
This problem is already 8 months old. Last time issue #190 has been closed but the problem is still here.

**Comment by nmnobre** [comment]
Did you edit your `config.plist` as in [here](https://github.com/jardenliu/XPS15-9560-BigSur/issues/196#issuecomment-835596005)?
