### ISSUE TITLE
Can this repository be used for macOS monterey?

### ISSUE THREAD

**Issue by SamGeens** [jardenliu/XPS15-9560-Ventura#208]
Is it save to update from Big Sur to macOS monterey on this repository?

**Comment by jardenliu** [comment]
No

**Comment by nmnobre** [comment]
Almost. Why so negative @jardenliu? 😝
I've been rocking Monterey with no problems whatsoever for almost a week now 🤓

1. Update to the latest version of [OpenCore](https://github.com/acidanthera/OpenCorePkg);
2. ~~Disable or remove both `FakePCIID.kext` and `FakePCIID_Intel_HDMI_Audio.kext`, which are currently incompatible with Monterey;~~ (as pointed out by @LeLunZ, this is already the case)
3. Update to the latest version of [BrcmPatchRAM](https://dortania.github.io/builds/?product=BrcmPatchRAM&viewall=true&version=2.6.1) and replace `BrcmBluetoothInjector.kext` with `BlueToolFixup.kext`;
4. Enable SIP by setting `csr-active-config` to `0x00000000`.

![OpenCore Configurator - Kexts Settings](https://user-images.githubusercontent.com/25757109/139557128-7793bb3a-f460-4fb3-95cc-60799d24c710.png)

![OpenCore Configurator - NVRAM Settings](https://user-images.githubusercontent.com/25757109/139557834-33c8e13b-5e5f-4e81-8cd3-f2f7ec332cb2.png)

You can read more about the issues with bluetooth and FakePCIID on [this GitHub repo for the XPS 15 9550](https://github.com/krim404/DellXPS15-9550-OSX/issues/167), [this thread at tonymacx86.com](https://www.tonymacx86.com/threads/guide-dell-xps-9560-big-sur-opencore.307163/post-2282575) or [the Acidanthera bugtracker Github repo](https://github.com/acidanthera/bugtracker/issues/1821).

**Comment by LeLunZ** [comment]
@nmnobre FakePCIID is already disabled.

![34A0503A-AF47-4275-8D40-9C9F3358288E](https://user-images.githubusercontent.com/31982496/139557589-1546a9db-a24a-49f5-8bb0-f7b1dbcf967d.png)

**Comment by jardenliu** [comment]
@nmnobre I've been busy lately. So this configuration was not updated in time.
Now it supported for Monterey
If you are free, Please create PR for this repo. Thanks

**Comment by jardenliu** [comment]
@SamGeens Now it work.
